name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15 ]

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15 ]

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Unit tests
        run: make test

  linters:
    name: Linters
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15 ]

    steps:
      - uses: actions/checkout@v2

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
          args: --timeout=5m
